Repository kymata-atlas/kymata-core, pull requests merged in 2024-08, with the labels that each got.

#347 Adds eSSS and eeg projection
  kymata/preproc/data_cleansing.py
  kymata/preproc/premorph.py
  kymata/preproc/source.py
Labels: 💪 enhancement

#353 Include the feature to convert to bids format with one invoker
  invokers/invoker_convert_to_bids.py
  kymata/io/bids.py
  kymata/preproc/hexel_current_estimation.py
  logs/.gitignore
  poetry.lock
Labels: 💪 enhancement

#355 Update plot.py
  kymata/plot/plot.py
Labels: 📈 plotting functionality, gridsearch

#325 Function to combine a list of ExpressionSets
  kymata/entities/expression.py
  kymata/io/functions.py
  tests/test_expression.py
Labels: 💪 enhancement, 📋 tests
