Repository kymata-atlas/kymata-core, pull requests merged in 2024-07, with the labels that each got.

#310 Remove medial wall hexels in order to improve source localisations
  kymata/preproc/data_cleansing.py
  kymata/preproc/hexel_current_estimation.py
Labels: 💪 enhancement, 🧠 source localisation

#312 Set random seed for gridsearch
  kymata/gridsearch/plain.py
Labels: 💪 enhancement, gridsearch

#315 Update data_cleansing.py
  kymata/preproc/data_cleansing.py
Labels: 💪 enhancement, give it a go!, one-line-fix, 🧠 source localisation

#319 Option to plot top five channels
  invokers/run_gridsearch.py
  kymata/gridsearch/plain.py
  submit_gridsearch.sh
Labels: 📈 plotting functionality, gridsearch

#317 Replace nans in function contours
  invokers/run_gridsearch.py
  kymata/io/functions.py
Labels: 🪲 bug, gridsearch

#320 Show only chosen sensors
  kymata/entities/expression.py
  kymata/plot/layouts.py
  kymata/plot/plot.py
Labels: 💪 enhancement, 📈 plotting functionality

#322 Refactor IPPM Plotter + Builder along with tests
  kymata/ippm/data_tools.py
  kymata/ippm/ippm.py
  kymata/ippm/ippm_builder.py
  kymata/ippm/ippm_plotter.py
  tests/test_ippm_builder.py
  tests/test_ippm_data_tools.py
  tests/test_ippm_plotter.py
Labels: ⚙️ refactor, IPPM generation

#324 Option to set expression plot title as argument
  kymata/plot/plot.py
Labels: 💪 enhancement, 📈 plotting functionality

#330 Better documentation on minimap view options
  kymata/plot/plot.py
Labels: 📑 documentation, 📈 plotting functionality

#333 More explicit error when an `ExpressionSet` is constructed with duplicate function names
  kymata/entities/expression.py
  tests/test_expression.py
Labels: ⚙️ refactor

#332 Option to specify fig_size
  kymata/plot/plot.py
Labels: 📈 plotting functionality

#341 Normalize bug
  invokers/run_gridsearch.py
  kymata/gridsearch/plain.py
  kymata/io/functions.py
  kymata/math/vector.py
Labels: 🪲 bug, gridsearch, 📋 tests

#346 Gridsearch normalize fix
  invokers/run_gridsearch.py
  kymata/gridsearch/plain.py
  kymata/io/functions.py
  kymata/math/vector.py
Labels: 🪲 bug, gridsearch
