Repository kymata-atlas/kymata-core, pull requests merged in 2025-05, with the labels that each got.

#470 IPPM graph connection options
  kymata/ippm/graph.py
  kymata/plot/ippm.py
Labels: IPPM generation

#392 Low-hanging dtype specification
  tests/test_datasets.py
  tests/test_expression.py
  tests/test_ippm_clusterers_unit_tests.py
Labels: 📋 tests

#485 Fix an out-by-one error on color-value lookups
  kymata/plot/brain.py
Labels: 📈 plotting functionality

#486 Small tidy of plotting code
  codecov.yml
  kymata/plot/brain.py
  kymata/plot/expression.py
  kymata/plot/sensor.py
Labels: ⚙️ refactor, 📋 tests

#488 Update run_gridsearch.py
  kymata/invokers/run_gridsearch.py
Labels: gridsearch, one-line-fix

#492 Update brain.py
  kymata/plot/brain.py
Labels: 📈 plotting functionality

#494 Dynamically position α* label on RHS
  kymata/plot/expression.py
Labels: 📈 plotting functionality, one-line-fix
